insert into users values(1);
insert into users values(2);
insert into users values(3);
insert into items values(1);
insert into items values(2);
insert into items values(3);
insert into basket(quantity,user_id,item_id) values(2,1,1);
insert into basket(quantity,user_id,item_id) values(3,1,2);
insert into basket(quantity,user_id,item_id) values(4,1,3);
